Refactor Jenkins pipeline to streamline Docker image build and deployment process

diff --git a/jenkinsFile b/jenkinsFile
--- a/jenkinsFile
+++ b/jenkinsFile
@@ -2,162 +2,141 @@ pipeline {
     agent any
 
     environment {
-        DOCKER_HUB_USER = 'parakkrama'
-        IMAGE_NAME = 'parakkrama/frontend'
-        CONTAINER_NAME = 'react_frontend'
-        SERVER_USER = 'ubuntu'
-        SERVER_HOST = ''
+     
+        DOCKER_CREDENTIALS_ID = "dockerhub-credentials"
+        // SSH_CREDENTIALS_ID = "homemate-dev-server"
+        // SSH_TARGET = "ubuntu@16.170.174.241"
+        REACT_APP_IMAGE = "chamaravishwajith644/react-frontend-is:latest"
 
-        AWS_ACCESS_KEY = credentials('aws_access_key')
-        AWS_SECRET_KEY = credentials('aws_seacret_key')
-        SSH_KEY_PATH = '/root/jenkinsKey.pem'
     }
 
-    triggers {
-        githubPush()
+    tools {
+        maven 'Maven 3.9.9'
     }
 
     stages {
-        stage('Copy Secret File') {
-            steps {
-                script {
-                    withCredentials([file(credentialsId: 'main_pem', variable: 'PEM_FILE')]) {
-                        sh 'cp $PEM_FILE $WORKSPACE/jenkinsKey.pem'
-                        sh 'chmod 600 $WORKSPACE/jenkinsKey.pem'
-                    }
-                }
-            }
-        }
-
-        stage('Terraform Init') {
-            steps {
-                script {
-                    sh '''
-                    export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
-                    export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
-                    terraform init
-                    '''
-                }
-            }
-        }
-
-        stage('Terraform Apply') {
-            steps {
-                script {
-                    sh '''
-                    terraform apply -auto-approve \
-                        -var="AWS_ACCESS_KEY=$AWS_ACCESS_KEY" \
-                        -var="AWS_SECRET_KEY=$AWS_SECRET_KEY"
-                    '''
-                }
-            }
-        }
-
-        stage('Fetch EC2 IP') {
-    steps {
-        script {
-            def ec2Ip = sh(script: 'terraform output -raw jenkins_public_ip', returnStdout: true).trim()
-            echo "Fetched EC2 IP: ${ec2Ip}"
-            
-            // ✅ Pass the IP directly in the SSH command instead of modifying env.SERVER_HOST
-            writeFile file: 'inventory.ini', text: """
-            [jenkins]
-            ${ec2Ip} ansible_user=ubuntu ansible_ssh_private_key_file=$WORKSPACE/jenkinsKey.pem ansible_python_interpreter=/usr/bin/python3
-            """
-
-            // ✅ Save to a temporary file
-            writeFile file: 'server_host.txt', text: ec2Ip
-        }
-    }
-}
-
         stage('Checkout Code') {
             steps {
-                git branch: 'deops_1', url: 'https://github.com/SDewthilini/url_shortner_fr.git'
+                git branch: 'main', url: 'https://github.com/SDewthilini/url_shortner_fr.git'
             }
         }
 
-        stage('Install Dependencies') {
-            steps {
-                sh 'npm install'
-            }
-        }
+       
 
-        stage('Build React App') {
-            steps {
-                sh 'npm run build'
-            }
-        }
+       
 
-        stage('Build Docker Image') {
+      
+
+       
+
+
+        stage('Build & Push Frontend Docker Image') {
             steps {
                 script {
-                    def imageTag = "${IMAGE_NAME}:${BUILD_NUMBER}"
-                    def latestTag = "${IMAGE_NAME}:latest"
-
-                    sh "docker build -t ${imageTag} -t ${latestTag} ."
-                }
-            }
-        }
-
-        stage('Login to Docker Hub') {
-            steps {
-                script {
-                    withCredentials([string(credentialsId: 'docker-hub-password', variable: 'DOCKER_HUB_PASS')]) {
-                        sh "echo ${DOCKER_HUB_PASS} | docker login -u ${DOCKER_HUB_USER} --password-stdin"
+                    withCredentials([usernamePassword(credentialsId: DOCKER_CREDENTIALS_ID, usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
+                        sh '''
+                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
+                        # Build the React frontend Docker image with no-cache to force rebuild
+                        docker build --no-cache -t $REACT_APP_IMAGE -f Dockerfile frontend
+                        # Push the Docker image to DockerHub
+                        docker push $REACT_APP_IMAGE
+                        docker logout
+                        '''
                     }
                 }
             }
         }
 
-        stage('Push Docker Image') {
+       
+
+        stage('Deploy Frontend Application') {
             steps {
                 script {
-                    def imageTag = "${IMAGE_NAME}:${BUILD_NUMBER}"
-                    def latestTag = "${IMAGE_NAME}:latest"
+                    sshagent([SSH_CREDENTIALS_ID]) {
+                        sh '''
+                        ssh -T -o StrictHostKeyChecking=no $SSH_TARGET <<EOF
+                        set -xe  # Enables debugging
 
-                    sh "docker push ${imageTag}"
-                    sh "docker push ${latestTag}"
+                        # Ensure the Docker network exists
+                        docker network inspect homemate-network >/dev/null 2>&1 || docker network create homemate-network
+
+                        # Pull the latest React frontend image
+                        docker pull $REACT_APP_IMAGE
+
+                        # Stop and remove any running instance of the frontend
+                        docker ps -q --filter "name=react-frontend" | grep -q . && docker stop react-frontend || true
+                        docker ps -aq --filter "name=react-frontend" | grep -q . && docker rm react-frontend || true
+
+                        # Run the container within the same network
+                        docker run --pull=always -d --restart always --name react-frontend --network homemate-network -p 3000:3000 $REACT_APP_IMAGE
+
+                        docker logout
+                        '''
+                    }
                 }
             }
         }
-stage('Deploy with Docker Compose on EC2') {
-    steps {
-        script {
-            def ec2Ip = readFile('server_host.txt').trim()  // Read EC2 IP from the file
-            
-            // Test SSH connectivity first
-            sh """
-            ssh -o StrictHostKeyChecking=no -i $WORKSPACE/jenkinsKey.pem -v $SERVER_USER@${ec2Ip} 'echo "SSH connection successful"'
-            """
-            
-            // Copy docker-compose.yml to EC2 instance with verbose output
-            sh """
-            scp -v -o StrictHostKeyChecking=no -i $WORKSPACE/jenkinsKey.pem docker-compose.yml $SERVER_USER@${ec2Ip}:/home/$SERVER_USER/
-            """
-            
-            // SSH into EC2 and run docker-compose
-            sh """
-            ssh -o StrictHostKeyChecking=no -i $WORKSPACE/jenkinsKey.pem $SERVER_USER@${ec2Ip} << 'EOF'
-sudo apt update -y
-sudo apt install -y docker-compose
 
-# Clear some disk space before proceeding
-sudo docker system prune -af
-
-# Navigate to the directory where docker-compose.yml is located
-cd /home/$SERVER_USER
-
-# Run docker-compose up
-sudo docker-compose up -d
-EOF
-            """
-        }
     }
-}
+
+    post {
+        always {
+            junit 'The-Home-Services-Booking-System/target/surefire-reports/TEST-*.xml'
+            plot csvFileName: 'test-duration.csv',
+                title: 'Test Execution Time',
+                group: 'Test Metrics',
+                style: 'line'
+            cleanWs()
+        }
+
+        success {
+            emailext(
+                to: 'sch.chamara@gmail.com',
+                subject: "✅ SUCCESS: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' Completed Successfully",
+                body: """
+                <html>
+                    <body style="font-family: Arial, sans-serif; background-color: #f9f9f9; color: #333;">
+                        <div style="max-width: 800px; margin: 0 auto; padding: 20px; background-color: #ffffff; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
+                            <h2 style="color: green;">🎉 Build Successful! 🎉</h2>
+                            <p style="font-size: 16px;">The job <b>${env.JOB_NAME}</b> build <b>#${env.BUILD_NUMBER}</b> has completed successfully.</p>
 
 
+                            <div style="text-align: center; margin-top: 30px;">
+                                <p style="font-size: 14px; color: #777;">Thank you for using our CI/CD pipeline. If you have any questions, feel free to reach out.</p>
+                            </div>
+                        </div>
+                    </body>
+                </html>
+                """,
+                mimeType: 'text/html',
+                replyTo: 'sch.chamara@gmail.com',
+                from: 'sch.chamara@gmail.com'
+            )
+        }
+
+        failure {
+            emailext(
+                to: 'sch.chamara@gmail.com',
+                subject: "❌ FAILURE: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' Failed",
+                body: """
+                <html>
+                    <body style="font-family: Arial, sans-serif; background-color: #f9f9f9; color: #333;">
+                        <div style="max-width: 800px; margin: 0 auto; padding: 20px; background-color: #ffffff; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
+                            <h2 style="color: red;">⚠️ Build Failed! ⚠️</h2>
+                            <p style="font-size: 16px;">The job <b>${env.JOB_NAME}</b> build <b>#${env.BUILD_NUMBER}</b> has failed.</p>
 
 
+                            <div style="text-align: center; margin-top: 30px;">
+                                <p style="font-size: 14px; color: #777;">Thank you for using our CI/CD pipeline. We are here to assist you.</p>
+                            </div>
+                        </div>
+                    </body>
+                </html>
+                """,
+                mimeType: 'text/html',
+                replyTo: 'sch.chamara@gmail.com',
+                from: 'sch.chamara@gmail.com'
+            )
+        }
     }
 }
